name: Release

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    env:
      PYTHONUNBUFFERED: '1'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.14'

      - name: Install build requirements
        run: |
          python -m pip install -e '.[tests,build]'

      - name: Run tests
        run: pytest -q

      - name: Build distributions
        run: |
          rm -rf dist || true
          python -m build --sdist --wheel

      - name: Build PyInstaller binary
        run: |
          python -OO -m PyInstaller -F j2tmpl/cli.py -n j2tmpl

      - name: Compute SHA256 checksum for binary
        run: |
          sha256sum dist/j2tmpl | awk '{print $1}' > dist/j2tmpl.sha256

      - name: Upload all artifacts to release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.release.tag_name }}
          generate_release_notes: true
          make_latest: "true"
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
