name: Release

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    env:
      PYTHONUNBUFFERED: '1'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.14'

      - name: Install build requirements
        run: |
          python -m pip install -e '.[tests,build]'

      - name: Run tests
        run: pytest -q

      - name: Build distributions
        run: |
          rm -rf dist || true
          python -m build --sdist --wheel

      - name: Build PyInstaller binary
        uses: addnab/docker-run-action@v3
        with:
          image: ghcr.io/yt-dlp/manylinux_2_28_x86_64-shared
          options: -v ${{ github.workspace }}:/github/workspace
          run: |
            curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
            /opt/shared-cpython-3.14/bin/python3.14 get-pip.py
            cd /github/workspace
            /opt/shared-cpython-3.14/bin/python3.14 -m pip install -e '.[build,binary]'
            /opt/shared-cpython-3.14/bin/python3.14 -OO -m PyInstaller -F j2tmpl/cli.py -n j2tmpl

      - name: Compute SHA256 checksum for binary
        run: |
          sha256sum dist/j2tmpl | awk '{print $1}' > dist/j2tmpl.sha256

      - name: Upload all artifacts to release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.release.tag_name }}
          generate_release_notes: true
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
